/*
 * (C) 2006, J. Federico Hernandez Scarso <fede.hernandez@gmail.com>
 */
#ifndef _OTP_H_
#define _OTP_H_

#include <security/pam_modules.h>

/**
 * Type of one time password.
 */
typedef enum otp_type {ALPHANUM, ALPHA, NUM} otp_type_t;

/**
 * otp_get_from_user(): Gets the otp entered by the user_name.
 *
 * @pamh: pam handler
 * @return otp
 */
inline const char *otp_get_from_user(pam_handle_t *pamh);

/**
 * otp_cmp(): Compares the otp entered by the user_name.
 * 
 * @otp_input: otp given by the user
 * @otp_gen: otp generated by the module
 * @len: otp length
 * @return: PAM_AUTH_ERR or PAM_SUCCESS
 */
inline int otp_cmp(const char *otp_input, const char *otp_gen, int len);

/**
 * otp_gen(): generates an random string
 *
 * @len: otp length
 * @type
 * @return: otp or null
 */
char *otp_gen(int len, otp_type_t type);

#endif
